# Generated by Django 2.1.3 on 2018-11-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('color1', models.CharField(max_length=200)),
                ('color2', models.CharField(max_length=200)),
                ('logo_img', models.CharField(max_length=200)),
                ('background_img', models.CharField(max_length=200)),
                ('espn_link', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
