# Generated by Django 2.1.3 on 2018-11-21 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espnid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl_database.Teams')),
            ],
            options={
                'verbose_name_plural': 'Players',
            },
        ),
    ]
