# Generated by Django 2.1.3 on 2018-11-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_database', '0002_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='image',
            field=models.CharField(default='link', max_length=200),
            preserve_default=False,
        ),
    ]
