class TeamDictionary:
	def __init__(self):
		self.kaggle_abbrev = {
			'Pittsburgh Steelers':'PIT',
			'Arizona Cardinals':'ARI',
			'Atlanta Falcons':'ATL',
			'Baltimore Ravens':'BAL',
			'Carolina Panthers':'CAR',
			'Cincinnati Bengals':'CIN',
			'Cleveland Browns':'CLE',
			'Green Bay Packers':'GB',
			'Houston Texans':'HOU',
			'Indianapolis Colts':'IND',
			'New Orleans Saints':'NO',
			'New York Giants':'NYG',
			'Seattle Seahawks':'SEA',
			'Tampa Bay Buccaneers':'TB',
			'New England Patriots':'NE',
			'Oakland Raiders':'OAK',
			'Buffalo Bills':'BUF',
			'Chicago Bears':'CHI',
			'Dallas Cowboys':'DAL',
			'Denver Broncos':'DEN',
			'Detroit Lions':'DET',
			'Jacksonville Jaguars':'JAX',
			'Kansas City Chiefs':'KC',
			'New York Jets':'NYJ',
			'Philadelphia Eagles':'PHI',
			'San Diego Chargers':'LAC',
			'San Francisco 49ers':'SF',
			'Tennessee Titans':'TEN',
			'Washington Redskins':'WAS',
			'Miami Dolphins':'MIA',
			'Minnesota Vikings':'MIN',
			'St. Louis Rams':'LAR',
			'Los Angeles Rams':'LAR',
			'Los Angeles Chargers':'LAC',
			'Houston Oilers':'HOU'
		}
		self.fantasy_pros = {
			'KC':'Kansas City Chiefs',
			'BAL':'Baltimore Ravens',
			'PIT':'Pittsburgh Steelers',
			'OAK':'Oakland Raiders',
			'NO':'New Orleans Saints',
			'TB':'Tampa Bay Buccaneers',
			'LAC':'Los Angeles Chargers',
			'CIN':'Cincinnati Bengals',
			'CAR':'Carolina Panthers',
			'CLE':'Cleveland Browns',
			'SEA':'Seattle Seahawks',
			'MIN':'Minnesota Vikings',
			'GB':'Green Bay Packers',
			'ATL':'Atlanta Falcons',
			'IND':'Indianapolis Colts',
			'HOU':'Houston Texans',
			'NE':'New England Patriots',
			'MIA':'Miami Dolphins',
			'LAR':'Los Angeles Rams',
			'STL':'St. Louis Rams',
			'CHI':'Chicago Bears',
			'DAL':'Dallas Cowboys',
			'PHI':'Philadelphia Eagles',
			'BUF':'Buffalo Bills',
			'NYJ':'New York Jets',
			'DET':'Detroit Lions',
			'ARI':'Arizona Cardinals',
			'DEN':'Denver Broncos',
			'SF':'San Francisco 49ers',
			'NYG':'New York Giants',
			'WAS':'Washington Redskins',
			'TEN':'Tennessee Titans',
			'JAC':'Jacksonville Jaguars'
		}
		self.rotoguru_abbrev = {
			'KAN':'Kansas City Chiefs',
			'BAL':'Baltimore Ravens',
			'PIT':'Pittsburgh Steelers',
			'OAK':'Oakland Raiders',
			'NO':'New Orleans Saints',
			'TAM':'Tampa Bay Buccaneers',
			'LAC':'Los Angeles Chargers',
			'CIN':'Cincinnati Bengals',
			'CAR':'Carolina Panthers',
			'CLE':'Cleveland Browns',
			'SEA':'Seattle Seahawks',
			'MIN':'Minnesota Vikings',
			'GB':'Green Bay Packers',
			'ATL':'Atlanta Falcons',
			'IND':'Indianapolis Colts',
			'HOU':'Houston Texans',
			'NE':'New England Patriots',
			'MIA':'Miami Dolphins',
			'LAR':'Los Angeles Rams',
			'CHI':'Chicago Bears',
			'DAL':'Dallas Cowboys',
			'PHI':'Philadelphia Eagles',
			'BUF':'Buffalo Bills',
			'NYJ':'New York Jets',
			'DET':'Detroit Lions',
			'ARI':'Arizona Cardinals',
			'DEN':'Denver Broncos',
			'SFO':'San Francisco 49ers',
			'NYG':'New York Giants',
			'WAS':'Washington Redskins',
			'TEN':'Tennessee Titans',
			'JAC':'Jacksonville Jaguars'
		}
		self.rotoguru_dsts = {
			'Arizona':'Arizona Cardinals',
			'Atlanta':'Atlanta Falcons',
			'Baltimore':'Baltimore Ravens',
			'Buffalo':'Buffalo Bills',
			'Carolina':'Carolina Panthers',
			'Chicago':'Chicago Bears',
			'Cincinnati':'Cincinnati Bengals',
			'Cleveland':'Cleveland Browns',
			'Dallas':'Dallas Cowboys',
			'Denver':'Denver Broncos',
			'Detroit':'Detroit Lions',
			'Green Bay':'Green Bay Packers',
			'Indianapolis':'Indianapolis Colts',
			'Jacksonville':'Jacksonville Jaguars',
			'Kansas City':'Kansas City Chiefs',
			'Miami':'Miami Dolphins',
			'Minnesota':'Minnesota Vikings',
			'New England':'New England Patriots',
			'New Orleans':'New Orleans Saints',
			'New York G':'New York Giants',
			'New York J':'New York Jets',
			'Oakland':'Oakland Raiders',
			'Philadelphia':'Philadelphia Eagles',
			'Pittsburgh':'Pittsburgh Steelers',
			'LA Rams':'Los Angeles Rams',
			'LA Chargers':'Los Angeles Chargers',
			'San Francisco':'San Francisco 49ers',
			'Seattle':'Seattle Seahawks',
			'Tampa Bay':'Tampa Bay Buccaneers',
			'Tennessee':'Tennessee Titans',
			'Washington':'Washington Redskins',
			'Houston':'Houston Texans'
		}
		self.espn_proj = {
			'KC':'Kansas City Chiefs',
			'BAL':'Baltimore Ravens',
			'PIT':'Pittsburgh Steelers',
			'OAK':'Oakland Raiders',
			'NO':'New Orleans Saints',
			'TB':'Tampa Bay Buccaneers',
			'LAC':'Los Angeles Chargers',
			'CIN':'Cincinnati Bengals',
			'CAR':'Carolina Panthers',
			'CLE':'Cleveland Browns',
			'SEA':'Seattle Seahawks',
			'MIN':'Minnesota Vikings',
			'GB':'Green Bay Packers',
			'ATL':'Atlanta Falcons',
			'IND':'Indianapolis Colts',
			'HOU':'Houston Texans',
			'NE':'New England Patriots',
			'MIA':'Miami Dolphins',
			'LAR':'Los Angeles Rams',
			'CHI':'Chicago Bears',
			'DAL':'Dallas Cowboys',
			'PHI':'Philadelphia Eagles',
			'BUF':'Buffalo Bills',
			'NYJ':'New York Jets',
			'DET':'Detroit Lions',
			'ARI':'Arizona Cardinals',
			'DEN':'Denver Broncos',
			'SF':'San Francisco 49ers',
			'NYG':'New York Giants',
			'WSH':'Washington Redskins',
			'TEN':'Tennessee Titans',
			'JAX':'Jacksonville Jaguars'
		}
		self.football_ref = {
			'ATL':'Atlanta Falcons',
			'PHI':'Philadelphia Eagles',
			'JAX':'Jacksonville Jaguars',
			'NYG':'New York Giants',
			'HOU':'Houston Texans',
			'NWE':'New England Patriots',
			'TAM':'Tampa Bay Buccaneers',
			'NOR':'New Orleans Saints',
			'SFO':'San Francisco 49ers',
			'MIN':'Minnesota Vikings',
			'TEN':'Tennessee Titans',
			'MIA':'Miami Dolphins',
			'CIN':'Cincinnati Bengals',
			'IND':'Indianapolis Colts',
			'PIT':'Pittsburgh Steelers',
			'CLE':'Cleveland Browns',
			'BUF':'Buffalo Bills',
			'BAL':'Baltimore Ravens',
			'KAN':'Kansas City Chiefs',
			'LAC':'Los Angeles Chargers',
			'SEA':'Seattle Seahawks',
			'DEN':'Denver Broncos',
			'WAS':'Washington Redskins',
			'ARI':'Arizona Cardinals',
			'DAL':'Dallas Cowboys',
			'CAR':'Carolina Panthers',
			'CHI':'Chicago Bears',
			'GNB':'Green Bay Packers',
			'NYJ':'New York Jets',
			'DET':'Detroit Lions',
			'LAR':'Los Angeles Rams',
			'STL':'St. Louis Rams',
			'OAK':'Oakland Raiders',
			'SDG':'San Diego Chargers'
		}

	def get_reverse_dict(dictionary):
		return dict([[v,k] for k,v in dictionary.items()])
